Clone99Cats/config/routes.rb
Rails.application.routes.draw do
  resources :cats do 
    resources :cat_rental_requests, only: :new
  end
  resources :cat_rental_requests, only: :create
end

Clone99Cats/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Clone99Cats/app/models/cat.rb
# == Schema Information
#
# Table name: cats
#
#  id          :bigint(8)        not null, primary key
#  birth_date  :date             not null
#  color       :string           not null
#  name        :string           not null
#  sex         :string(1)        not null
#  description :text             not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Cat < ApplicationRecord
  COLORS =  ["Tortoiseshell","Calico","Orange Taby",
             "Brown Tabby", "Gray Tabby", "Black",
             "Gray", "White", "Tuxedo", "Black and White"]

  validates :birth_date, :color, :name, :sex, :description, presence: true
  validates :color, inclusion: { in: COLORS }
  validates :sex, inclusion: { in: %w(M F) }

  has_many :cat_rental_requests,
    primary_key: :id,
    foreign_key: :cat_id,
    class_name: :CatRentalRequest,
    dependent: :destroy

  def age
    year = Date.today.year - birth_date.year
    month = Date.today.month - birth_date.month
    if month.abs > 6
      "#{name} is almost #{year+1}"
    elsif year < 1
      "#{name} is #{month} months old"
    else
      "#{name} is #{year} years old"
    end
  end
end

Clone99Cats/app/models/cat_rental_request.rb
# == Schema Information
#
# Table name: cat_rental_requests
#
#  id         :bigint(8)        not null, primary key
#  cat_id     :integer
#  start_date :date             not null
#  end_date   :date             not null
#  status     :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class CatRentalRequest < ApplicationRecord
  STATUSES = %w(PENDING APPROVED DENIED)

  validates :start_date, :end_date, :status, presence: true
  validates :status, inclusion: { in: STATUSES }
  validate :does_not_overlap_approved_request

  belongs_to :cat,
    primary_key: :id,
    foreign_key: :cat_id,
    class_name: :Cat

  def does_not_overlap_approved_request
    unless overlapping_approved_request.empty?
      raise errors[:cat_id] << "is already rented out"
    end
  end

  def overlapping_approved_request
    overlapping_requests("APPROVED")
  end
  
  def overlapping_requests(status)
    # cats =SELECT *
    # FROM cat_rental_requests
    # WHERE cat_rental_requests.cat_id = cat_id 
    # AND cat_rental_requests.status = "APPROVED"
    CatRentalRequest.where(cat_id: cat_id).where(status: status)
  end
end

Clone99Cats/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

Clone99Cats/app/controllers/cat_rental_requests_controller.rb
class CatRentalRequestsController < ApplicationController
  def new
    @cat_rental_request = CatRentalRequest.new(cat_id: params[:cat_id])
    render :new
  end

  def create
    render json: params
  end
end

Clone99Cats/app/controllers/cats_controller.rb
class CatsController < ApplicationController

  def index
    @cats = Cat.all
  end

  def show
    @cat = Cat.find(params[:id])
  end

  def new
    @cat = Cat.new
  end

  def create
    render json: params
  end

  def edit
    @cat = Cat.find(params[:id])
  end 

  def update
    render json: params
  end
end

Clone99Cats/app/helpers/application_helper.rb
module ApplicationHelper
end

Clone99Cats/app/helpers/cat_rental_requests_helper.rb
module CatRentalRequestsHelper
end

Clone99Cats/app/helpers/cats_helper.rb
module CatsHelper
end

Clone99Cats/app/views/cat_rental_requests/new.html.erb
<form action="<%= cat_rental_requests_url %>" method="post">
  <input type="hidden" name="cat_rental_request[cat_id]" value="<%= @cat_rental_request.cat_id %>" >

  <label for="start_date">
    <input type="date" name="cat_rental_request[start_date]" value="<%= @cat_rental_request.start_date %>" >
  </label>

  <label for="end_date">
    <input type="date" name="cat_rental_request[end_date]" value="<%= @cat_rental_request.end_date %>" >
  </label>

  <label for="status">
    <select name="cat_rental_request[status]">
      <% CatRentalRequest::STATUSES.each do |status| %>
        <option value="<%= status %>"> <%= status %> </option>
      <% end %>
    </select>
  </label>

  <input type="submit" value="Create Rental Request">
</form>

Clone99Cats/app/views/cats/_form.html.erb
<% if cat.persisted? %>
  <% action_url = cat_url(cat) %>
  <% submit_value = 'Update' %>
<% else %>
  <% action_url = cats_url %>
  <% submit_value = 'Create' %>
<% end %>

<form action="<%= action_url %>" method="post">
  <% if cat.persisted? %>
    <input type="hidden" name="_method" value="patch">
  <% end %>

  <label for="name">Name:
    <input type="text" name="name" value="<%= cat.name %>">
  </label>
  <br>

  <label for="birth_date">Birth Date:
    <input type="date" name="birth_date" value="<%= cat.birth_date %>">
  </label>
  <br>

  <label for="color">Color:
    <select name="color">
      <option selected disabled>Color</option>
      <% Cat::COLORS.each do |color| %>
        <option value="<%= color %>" <%= cat.color == color ? "selected" : ""%> ><%= color %></option>
      <% end %>
    </select>
  </label>
  <br>

  <p>Sex: </p>
  <label for="M">
    <input id="M" type="radio" name="sex" value="M" <%= cat.sex == "M" ? "checked" : "" %> >M
  </label>

  <label for="F">
    <input id="F"  type="radio" name="sex" value="F" <%= cat.sex == "F" ? "checked" : "" %> >F
  </label>

  <br>

  <label for="description">Description:
    <textarea name="description">
      <%= cat.description %>
    </textarea>
  </label>
  <br>

  <input type="submit" value="<%= submit_value %>">
</form>

Clone99Cats/app/views/cats/edit.html.erb
<h2>Edit a cat</h2>
<%= render 'form', cat: @cat %>

Clone99Cats/app/views/cats/index.html.erb
<h1>Cats#index</h1>
<!-- <p>Find me in app/views/cats/index.html.erb</p> -->

<ol>
  <% @cats.each do |cat| %>
    <li>
      <ul>
        <li><%= cat.name %></li>
        <li><%= cat.age %></li>
        <li><%= cat.birth_date %></li>
        <li><%= cat.color %></li>
        <li><%= cat.sex %></li>
        <li><%= cat.description %></li>
      </ul>
      <br>
    </li>
  <% end %>
</ol>

Clone99Cats/app/views/cats/new.html.erb
<h2>Create a cat</h2>
<%= render 'form', cat: @cat %>

Clone99Cats/app/views/cats/show.html.erb
<h1>Cats#show</h1>

<h2><%= @cat.name %></h2>
<table> 
  <thead>
    <tr>
      <td>Attribute</td>
      <td>Value</td>
    </tr>
  </thead>
  <tr>
    <td>age</td>
    <td><%= @cat.age %></td>
  </tr>
  
  <tr>
    <td>birth_date</td>
    <td><%= @cat.birth_date %></td>
  </tr>

  <tr>
    <td>color</td>
    <td><%= @cat.color %></td>
  </tr>

  <tr>
    <td>sex</td>
    <td><%= @cat.sex %></td>
  </tr>
</table>

Clone99Cats/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Clone99Cats</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>